### ISSUE TITLE
Need help using this.

### ISSUE THREAD

**Issue by vrajneesh** [fmonthel/radosgw-admin-mng-tools#1]
Seems very useful utilties for managing the radosgw and object stores..

Downloaded the files.. Installed the pip libraries.

Not sure which user i should pick from radosgw-admin metadata list user command for the config.ini file.

here is config file and error I am getting..

# User must have CAPS users=*,buckets=*,metadata=*,usage=*
[RGW]
rgw_server: lshtrgw001a.xxx.xxx.com
rgw_access_key: LPU5K2XOJNC907QBIE6R
rgw_secret_key: 5bmSI7FXkh62l85jvLcFuGN7bKwacTnyZgD571FR

[ACCOUNT]
account_env: testgwuser

[root@lshtrgw001a radosgw-admin-mng-tools-master]# ./list-accounts.py
Traceback (most recent call last):
  File "./list-accounts.py", line 36, in <module>
    dUsers = radosgw.get_users()
  File "/usr/lib/python2.7/site-packages/rgwadmin/rgw.py", line 227, in get_users
    return self.get_metadata(metadata_type='user')
  File "/usr/lib/python2.7/site-packages/rgwadmin/rgw.py", line 176, in get_metadata
    headers=headers,
  File "/usr/lib/python2.7/site-packages/rgwadmin/rgw.py", line 159, in _request_metadata
    data=data
  File "/usr/lib/python2.7/site-packages/rgwadmin/rgw.py", line 144, in request
    return self._load_request(r)
  File "/usr/lib/python2.7/site-packages/rgwadmin/rgw.py", line 124, in _load_request
    raise e(j)
rgwadmin.exceptions.AccessDenied

Thanks for your help in advance..

**Comment by vrajneesh** [comment]
started working.. seems had some caps issues.. Really nice utilities.. thanks for sharing them on github.

**Comment by vrajneesh** [comment]
Thanks
